### PR TITLE
Spanish translation of the repository content

### PR DESCRIPTION
**Pull request by JoseDeFreitas**
Hello 👋!
I've translated all text (from English) into Spanish (es_ES). The only things that weren't translated: title of the readme and link placeholders.
According to the other branches, I've created the "es_ES" branch. As I see it shouldn't be merged into "main" but instead keep it as a separate branch.

### CODE REVIEW

**Comment by JoseDeFreitas** [comment]
Issue corresponding to this pull request: #9.

**Review by mbiesiad — APPROVED** [review]
LGTM  🦄

**Comment by mbiesiad** [comment]
Hi @JoseDeFreitas  Awesome!! Thanks a lot for your effort here ⭐ That is impressive!

Unfortunately I had to revert changes. The PR changed the main readme.md file.

Sorry, my fault (too fast & before first coffee), that I didn't check.. ☕ Btw, that's great because I know Spanish basics, so I had an opportunity to remind a little bit. Thanks again!

I fixed this, the Spanish version was added & given link to your repo. Is it fine for you?

Best wishes,

**Comment by JoseDeFreitas** [comment]
Hello @mbiesiad!
Thank you a lot for your comments.
About the other thing, there's no problem. It was my fault first as I created the es_ES branch from the main branch and started working but then I realized you couldn't of course merge it 🤦‍♂️. If you want you can create the branch by yourself in your repo and just copy the text I wrote in the readme file of my es_ES. If not I can keep the repo so people can access it, no problem at all, it's fine.
As I said, thank you for your good comments. Hope you have an awesome day 😄.

**Pull request merged**
