### PR TITLE
Update RTranslator description

### PR DESCRIPTION
**Pull request by niedev**
Hi @mbiesiad!

I finally managed to get rid of the Google APIs 😁, so I wanted to update the description

### CODE REVIEW

**Review by mbiesiad — COMMENTED** [review]
Needed tiny change with "NLLB e Whisper" (typo)

**Comment by mbiesiad** [comment]
Hi @niedev Sounds great! 🔥 I'm curious, so I will take a look ASAP (at [RTranslator](https://github.com/niedev/RTranslator)) 🚀
 
Initial review - Needed tiny change with "NLLB e Whisper", if you want, I can correct it in the next few days (weekend is coming) 😅 so, I can approve now, and fix the typo soon (or maybe you want to do it yourself sooner; please feel free to let me know).

**Comment by niedev** [comment]
Sorry for the mistake, the Italian came out 😂, fixed 👍

**Review by mbiesiad — APPROVED** [review]
LGTM ✨

**Comment by mbiesiad** [comment]
All is fine, really great work with RTranslator! 🚀 Thanks a lot for your time, quick action and professional approach 🎉 Ti auguro il meglio

**Comment by niedev** [comment]
Thank you 🚀 I like how this awesome list has grown, and really liked also awesome-astronomy. Really good job! Życzę ci też wszystkiego najlepszego (translated with RTranslator, I hope it is good 😁)

**Pull request merged**
